name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide details about your idea.

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Model Architecture Improvement
        - Performance Optimization
        - New Dataset Support
        - Hardware Platform Support
        - Visualization Enhancement
        - Documentation Improvement
        - Developer Tools
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem or limitation you're facing
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see implemented?
      placeholder: Describe your proposed solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: Describe alternative solutions you've considered

  - type: textarea
    id: benefits
    attributes:
      label: Expected Benefits
      description: How would this feature improve the project?
      placeholder: |
        - Performance improvement: ...
        - Usability enhancement: ...
        - New capabilities: ...

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Considerations
      description: Are you willing to help implement this feature?
      options:
        - label: I would be willing to implement this feature
        - label: I can provide testing and feedback
        - label: I can help with documentation

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional context, mockups, or references
