name: Code Quality

permissions:
  contents: read

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint-python:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort
        # Install project dependencies if requirements.txt exists
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Treat all errors as warnings, GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Check code formatting with black
      run: |
        black --check --diff .
    
    - name: Check import sorting with isort
      run: |
        isort --check-only --diff .

  lint-latex:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install LaTeX linting tools
      run: |
        sudo apt-get update
        sudo apt-get install -y chktex lacheck
    
    - name: Lint LaTeX files
      run: |
        # Check LaTeX syntax
        chktex -v3 *.tex || true
        lacheck *.tex || true
    
    - name: Check for TODO/FIXME comments
      run: |
        echo "Checking for TODO/FIXME comments..."
        grep -rn "TODO\|FIXME\|XXX" --include="*.tex" --include="*.py" . || echo "No TODO/FIXME found"

  check-links:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install markdown link checker
      run: npm install -g markdown-link-check
    
    - name: Check links in README
      run: |
        markdown-link-check README.md --config .github/mlc_config.json || true
    
    - name: Check links in CONTRIBUTING
      run: |
        markdown-link-check CONTRIBUTING.md --config .github/mlc_config.json || true
